---
# RDS DB Instance template for MariaDB
#
# Required:
#
# - Eucalyptus container image
# - Bucket name for container registry storage
# - Instance profile for bucket read
# - VPC and subnet for creating resources in
# - Volume for data
#
# Optional:
#
# - MariaDB parameters
# - Instance type
# - SSH key name allowing debug connection to db instance
#
# MariaDB parameters as per RDS.
#
AWSTemplateFormatVersion: 2010-09-09
Description: MariaDB database instance template

Parameters:

  MariadbUser:
    Description: MariaDB user
    Type: String
    Default: mariadb

  MariadbPassword:
    Description: MariaDB password
    Type: String
    Default: ""

  MariadbDatabase:
    Description: MariaDB database
    Type: String
    Default: mariadb

  MariadbVersion:
    Description: MariaDB version
    Type: String
    Default: 10.5

  MariadbPort:
    Description: MariaDB listen port
    Type: String
    Default: 3306

  BucketName:
    Description: S3 bucket for container registry storage
    Type: String

  ImageId:
    Description: Identifier for the Eucalyptus Container image
    Type: String

  InstanceProfile:
    Description: Instance profile to use
    Type: String

  InstanceType:
    Description: Instance type to use
    Type: String
    Default: t2.small

  KeyName:
    Description: EC2 keypair for instance SSH access
    Type: String
    Default: ''

  SubnetId:
    Description: The subnet to use
    Type: String

  VolumeId:
    Description: The volume to use for database content
    Type: String

  VpcId:
    Description: The vpc to use
    Type: String

Conditions:

  UseKeyNameParameter: !Not
    - !Equals
      - !Ref KeyName
      - ''

Resources:

  WaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: !Ref WaitConditionHandle
      Timeout: 1800

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MariaDB security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: !Ref MariadbPort
          ToPort: !Ref MariadbPort
          CidrIp: "0.0.0.0/0"

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !If
        - UseKeyNameParameter
        - !Ref 'KeyName'
        - !Ref 'AWS::NoValue'
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref SecurityGroup
      Volumes:
        - VolumeId: !Ref VolumeId
          Device: /dev/sdf
      UserData:
        Fn::Base64: !Sub |
          #cloud-config
          bootcmd:
          - test ! -z "$(blkid /dev/vdb)" || mkfs -t ext4 -L euca-rdsfs /dev/vdb
          - test -d /var/mnt/rds || mkdir -pv /var/mnt/rds
          mounts:
          - ["/dev/vdb", "/var/mnt/rds", "ext4", "defaults,nofail", "0", "2"]
          write_files:
          - path: /etc/udev/rules.d/53-ec2-network-interfaces.rules
            permissions: "0644"
            owner: root
            content: |
              ACTION=="add", SUBSYSTEM=="net", KERNEL=="eth*", TAG+="systemd", ENV{SYSTEMD_WANTS}+="ec2net-ifup@$env{INTERFACE}"
              ACTION=="remove", SUBSYSTEM=="net", KERNEL=="eth*", RUN+="/usr/sbin/ec2ifdown $env{INTERFACE}"
          - path: /etc/systemd/system/ec2net-ifup@.service
            permissions: "0644"
            owner: root
            content: |
              [Unit]
              Description=Enable elastic network interfaces %i
              After=network-online.target
              BindsTo=sys-subsystem-net-devices-%i.device
              ConditionPathExists=!/var/run/dhclient-%i.pid
              [Service]
              RemainAfterExit=true
              ExecStart=/usr/sbin/ec2ifup %i
              ExecStop=/usr/sbin/ec2ifdown %i
          - path: /etc/containers/registries.conf
            permissions: "0644"
            owner: root
            content: |
              [[registry]]
              prefix = "docker.io"
              location = "127.0.0.1:5000"
              insecure = true
          - path: /etc/sysconfig/registry-container-bucket
            permissions: "0644"
            owner: root
            content: |
              REGISTRY_STORAGE_S3_BUCKET=${BucketName}
          - path: /usr/local/bin/registry-container-start
            permissions: "0755"
            owner: root
            content: |
              #!/bin/bash
              # Load registry image and start system registry service
              set -eux
              podman load docker.io/library/registry:2 < \
                  /usr/local/share/registry-container/registry.tar
              podman create --name registry \
                  --env-file /etc/sysconfig/registry-container \
                  --env-file /etc/sysconfig/registry-container-bucket \
                  --env-file /etc/sysconfig/registry-container-readonly \
                  --publish 127.0.0.1:5000:5000 \
                  docker.io/library/registry:2
              podman generate systemd --name --timeout 60 --restart-policy always registry > \
                  /etc/systemd/system/registry-container.service
              systemctl enable --now registry-container.service
          - path: /etc/sysconfig/mariadb-container
            permissions: "0644"
            owner: root
            content: |
              MARIADB_VERSION=${MariadbVersion}
              MARIADB_DB=${MariadbDatabase}
              MARIADB_PORT=${MariadbPort}
              MARIADB_USER=${MariadbUser}
              MARIADB_PASSWORD=${MariadbPassword}
          - path: /usr/local/bin/mariadb-container-start
            permissions: "0755"
            owner: root
            content: |
              #!/bin/bash
              # Create mariadb container and systemd service
              set -eux
              source /etc/sysconfig/mariadb-container
              mkdir -pv /var/mnt/rds/data
              podman create --name mariadb \
                  --env MYSQL_RANDOM_ROOT_PASSWORD="yes" \
                  --env MYSQL_DATABASE="${!MARIADB_DB}" \
                  --env MYSQL_USER="${!MARIADB_USER}" \
                  --env MYSQL_PASSWORD="${!MARIADB_PASSWORD}" \
                  --network host \
                  --volume /var/mnt/rds/data:/var/lib/mysql:z \
                  docker.io/library/mariadb:${!MARIADB_VERSION}
              podman generate systemd --name --timeout 60 --restart-policy always mariadb > \
                  /etc/systemd/system/mariadb-container.service
              systemctl enable --now mariadb-container.service
          - path: /usr/local/bin/rds-up
            permissions: "0755"
            owner: root
            content: |
              #!/bin/bash
              set -eux
              WAITCONDURL="${WaitConditionHandle}"
              COND_STATUS="FAILURE"
              COND_DATA="unknown"
              COND_REASON="Initialization failure"
              function cleanup {
                curl -s -X PUT -H "Content-Type:" \
                  --data-binary '{"Status": "'"${!COND_STATUS}"'", "UniqueId": "init", "Data": "'"${!COND_DATA}"'", "Reason": "'"${!COND_REASON}"'" }' \
                  ${!WAITCONDURL}
              }
              trap cleanup EXIT
              COND_DATA="registry-container"
              systemctl is-active --quiet registry-container.service
              COND_DATA="mariadb-container"
              systemctl is-active --quiet mariadb-container.service
              COND_DATA="ec2net-ifup@eth1"
              [ ! -r /etc/udev/rules.d/75-persistent-net-generator.rules ] || rm -fv /etc/udev/rules.d/75-persistent-net-generator.rules
              [ ! -r /sys/class/net/eth1 ] || systemctl enable --now ec2net-ifup@eth1.service
              COND_REASON="Cleanup failure"
              COND_DATA="registry-container"
              systemctl stop registry-container.service
              COND_STATUS="SUCCESS"
              COND_DATA="none"
              COND_REASON="completed"
          runcmd:
          - /usr/local/bin/registry-container-start
          - /usr/local/bin/mariadb-container-start
          - /usr/local/bin/rds-up

Outputs:

  InstanceId:
    Description: MariaDB instance identifier
    Value: !Ref Instance

  PrivateIp:
    Description: MariaDB instance private ip
    Value: !GetAtt Instance.PrivateIp
