#!/usr/bin/env python
import sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin import EucaAdmin
from optparse import OptionParser
from euca_admin.groups import Group

def main():
  c = Group().cli_add()
  sys.exit()

if __name__ == "__main__":
    main()
 
