#!/usr/bin/env python
import getopt, sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin.properties import Property

def main():
  c = Property()
  (options, args) = c.parse_modify()
  c.modify(options.props)
  sys.exit()

if __name__ == "__main__":
  main()
 
