#!/usr/bin/env python
import sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin import EucaAdmin
from euca_admin.walruses import Walrus
from optparse import OptionParser

def main():
  c = Walrus()
  parser = c.get_register_parser()
  (options, args) = parser.parse_args()
  c.register('walrus',options.walrus_host,options.walrus_port)
  sys.exit()

if __name__ == "__main__":
    main()
 
