#!/usr/bin/env python
import sys, os, boto
from euca_admin import local
from optparse import OptionParser

def main():
  parser = OptionParser("usage: %prog FILENAME",version="Eucalyptus %prog VERSION",description="Download the admin credentials for the locally hosted Eucalyptus installation")
  (options,args) = parser.parse_args()
  if len(args) != 1:
    parser.print_help()
    sys.exit()
  local.get_credentials(args[0])
  sys.exit()

if __name__ == "__main__":
    main()
 
