#!/usr/bin/env python
import sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin import EucaAdmin
from euca_admin.clusters import Cluster
from optparse import OptionParser

def main():
  c = Cluster().cli_deregister()
  sys.exit()

if __name__ == "__main__":
    main()
 
