#!/usr/bin/env python
import sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin import EucaAdmin
from euca_admin.clusters import Cluster
from optparse import OptionParser

def main():
  c = Cluster()
  parser = c.get_register_parser()
  (options, args) = parser.parse_args()
  c.register(options.cc_name,options.cc_host,options.cc_port)
  sys.exit()

if __name__ == "__main__":
    main()
 
