#!/usr/bin/env python
import getopt, sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin.nodes import Node

def main():
  c = Node().cli_describe()
  sys.exit()

if __name__ == "__main__":
  main()
 
