#!/usr/bin/env python
import sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin import EucaAdmin
from euca_admin.users import User
from optparse import OptionParser

def main():
  c = User()
  parser = c.get_add_parser()
  (options, args) = parser.parse_args()
  c.add(options.userName,options.email,options.admin)
  sys.exit()

if __name__ == "__main__":
    main()
 
