#!/usr/bin/env python
import sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin import EucaAdmin
from euca_admin.storagecontrollers import StorageController
from optparse import OptionParser

def main():
  c = StorageController()
  parser = c.get_register_parser()
  (options, args) = parser.parse_args()
  c.register(options.sc_name,options.sc_host,options.sc_port)
  sys.exit()

if __name__ == "__main__":
    main()
 
