#!/usr/bin/env python
import getopt, sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin.users import User

def main():
  c = User()
  parser = c.get_describe_parser()
  (options, args) = parser.parse_args()
  c.describe()
  sys.exit()

if __name__ == "__main__":
  main()
 
