#!/usr/bin/env python
import sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin import EucaAdmin
from optparse import OptionParser
from euca_admin.groups import Group

def main():
  c = Group()
  parser = c.get_grant_authorize_parser()
  (options, args) = parser.parse_args()
  c.grant_authorize(options.groupName,options.zoneName)
  sys.exit()

if __name__ == "__main__":
    main()
 
