#!/usr/bin/env python
import sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin import EucaAdmin
from euca_admin.groups import Group

def main():
  Group().cli_remove_membership()
  sys.exit()

if __name__ == "__main__":
    main()
 
