#!/usr/bin/env python
import sys, os, boto
from euca_admin import EucaAdmin
from euca_admin.component import ConvertVolumes 
from optparse import OptionParser

def main():
  c = ConvertVolumes()
  parser = c.get_parser()
  (options, args) = parser.parse_args()
  c.execute(options.sc_host, options.provider)
  sys.exit()

if __name__ == "__main__":
    main()
 
