#!/usr/bin/env python
import getopt, sys, os, boto
from boto.ec2.regioninfo import RegionInfo
from euca_admin.clusters import Cluster

def main():
  c = Cluster()
  c.describe()
  sys.exit()

if __name__ == "__main__":
  main()
 
