#!/bin/bash
#
# Copyright 2017 Ent. Services Development Corporation LP
#
# Redistribution and use of this software in source and binary forms,
# with or without modification, are permitted provided that the
# following conditions are met:
#
#   Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer
#   in the documentation and/or other materials provided with the
#   distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Service control script for Eucalyptus Cassandra
#
# Usage: euca-cassandra-ctl start|stop|status|clean
#
# start  - start service, do nothing if started
# stop   - stop service, do nothing if stopped
# status - check status of service, nonzero exit code for error
#          clean required exit code 1 or 2
#          stopped service exit code 3
# clean  - perform clean up related to bad status
#

. /etc/rc.d/init.d/functions

PID_FILE="/var/run/eucalyptus/cassandra.pid"
LOCK_FILE="/var/run/eucalyptus/cassandra.lock"

case "$1" in
    start)
        systemctl start eucalyptus-cloud-cassandra
        exit $?
        ;;
    stop)
        systemctl stop eucalyptus-cloud-cassandra
        exit $?
        ;;
    status)
        status -p $PID_FILE -l $LOCK_FILE eucalyptus-cassandra
        exit $?
        ;;
    clean)
        [ -f $PID_FILE ] && rm -f $PID_FILE
        [ -f $LOCK_FILE ] && rm -f $LOCK_FILE
        ;;
    *)
        echo "Usage: `basename $0` start|stop|status|clean"
        exit 1
esac

exit 0
