package edu.ucsb.eucalyptus.cloud;

/**
 * Fix for EUCA-2782. Interface for exceptions generated by HEAD requests in Walrus. Exceptions originating from the Walrus HEAD requests should implement this
 * interface. The purpose of this interface is to detect the type of exception in Walrus Outbound Handler before constructing the HTTP response body.
 * 
 * @author Swathi Gangisetty
 * 
 */
public interface HeadExceptionInterface {

}
