#
# Makefile for vmware-broker
#

all:
	$(MAKE) -C imager all

clean:
	$(MAKE) -C imager clean

distclean:
	$(MAKE) -C imager distclean

install:
	$(MAKE) -C imager install

deploy:
	$(MAKE) -C imager deploy

uninstall:
	$(MAKE) -C imager uninstall

build: all
