#!/bin/sh
#
# This script checks whether SELinux is currently in enforcing mode,
# and also whether it would be in enforcing mode the next time the system
# reboots.  If currently enforcing, returns a failure.  If it would be
# enforcing upon reboot, it returns success, but with a warning.
#
# Copyright 2013-2014 Eucalyptus Systems, Inc.
#
# Redistribution and use of this software in source and binary forms,
# with or without modification, are permitted provided that the following
# conditions are met:
#
#   Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

print_kv() {
  while true; do
    echo -n "\"$1\": \"$2\""
    shift 2
    if (( "$#" )); then echo -n ', '; else break; fi
  done
}

CURRENT=$( getenforce )
FAILED=0
if [ "$CURRENT" == "Enforcing" ]; then
  FAILED=1
fi

if [ -f /etc/sysconfig/selinux ]; then
  . /etc/sysconfig/selinux
fi

# Get args for the default kernel
ARGS=$( grubby --info $( grubby --default-kernel ) | grep ^args )
# default is enabled if selinux=0 is not specified
BOOT=$( echo $ARGS | sed 's/.*selinux=\([0|1]\)/\1/;tx;s/.*/1/;:x' )

if [ "$BOOT" == "1" ] && [ "$SELINUX" == "enforcing" ]; then
  WARN='SELinux is enabled and enforcing upon reboot'
fi

echo -n '{ '
print_kv "failed" "$FAILED" \
         "current" "$CURRENT" \
         "sysconfig" "$SELINUX" \
         "boot" "$BOOT"
if [ -n "$WARN" ]; then
  echo -n ', '
  print_kv "warn" "$WARN" \
           "resolution" "Set 'SELINUX' to 'permissive' in /etc/sysconfig/selinux"
fi
echo -n ' }'
