#!/bin/sh

### BEGIN INIT INFO
# Provides:          eucalyptus-console
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Eucalyptus Console Server
# Description:       Eucalyptus Console Server
### END INIT INFO

. /etc/rc.d/init.d/functions

[ -f /etc/sysconfig/eucalyptus-console ] && . /etc/sysconfig/eucalyptus-console

SERVICE=eucalyptus-console
PROCESS=euca-console-server
PIDFILE=/var/run/eucalyptus-console.pid

LOCKFILE=/var/lock/subsys/eucalyptus-console

start() {
    if [ "x${GENERATE_CERT}" != "xNO" ]; then
        generate_cert && generate_secret
    fi

    echo -n $"Starting $SERVICE: "
    daemon --pidfile=$PIDFILE $PROCESS -d
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    return $RETVAL
}

stop() {
    echo -n $"Stopping $SERVICE: "
    killproc -p $PIDFILE $PROCESS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
    [ -f $PIDFILE ] && rm -f $PIDFILE
}

restart() {
    stop
    start
}

generate_cert() {
    local key=/etc/eucalyptus-console/console.key
    local cert=/etc/eucalyptus-console/console.crt

    if [ -f $key ] && [ -f $cert ]; then
        return 1
    fi

    echo -n $"Generating self-signed certificate: "
    rm -f $key $cert

    local csr=`mktemp`
    local cn=

    if nslookup `hostname` &>/dev/null; then
        cn=$(nslookup `hostname` 2>&1 | tail -3 | grep Name | sed -e 's@^Name:\s*@@')
    else
        cn=`hostname`
    fi

    local country=US
    local state=CA
    local location="Santa Barbara"
    local org="Eucalyptus Systems, Inc."
    local unit="Eucalyptus User Console"

    if ! openssl genpkey -algorithm rsa -pkeyopt rsa_keygen_bits:2048 -out $key &>/dev/null; then
        rm -f $csr
        failure $"Generating RSA key"
        echo
        exit 1
    fi

    openssl req -new -key $key -sha512 -out $csr &>/dev/null <<EOF
$country
$state
$location
$org
$unit
$cn
$USER@$cn


EOF

    if [ $? -ne 0 ]; then
        rm -f $key $csr
        failure $"Generating certificate request"
        echo
        exit 1
    fi

    if ! openssl x509 -req -in $csr -signkey $key -days 365 -sha512 -out $cert &>/dev/null; then
        rm -f $key $csr
        failure $"Generating certificate"
        echo
        exit 1
    fi

    rm -f $csr

    chmod 600 $cert
    chmod 600 $key

    success $"Generating certificate"
    echo
}

generate_secret() {
    echo -n $"Generating cookie secret: "
    local secret=$(dd if=/dev/random count=16 bs=1 2>/dev/null | openssl md5 | cut -d' ' -f2)

    if [ $? -ne 0 ]; then
        failure $"Generating cookie secret"
        echo
        exit 1
    fi

    if ! sed -i "s/^cookie\.secret:.*$/cookie.secret: $secret/" \
            /etc/eucalyptus-console/console.ini &>/dev/null; then
        failure $"Writing cookie secret"
        echo
        exit 1
    fi

    success $"Generating cookie secret"
    echo
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p $PIDFILE $PROCESS
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 2
esac
exit $RETVAL

