#!/bin/bash
#

usage () {
	# euca_sync_key is dead
	echo
	echo "euca_sync_key is deprecated: use euca_conf (-synckeys or -addnode)"
	echo
}

KEYS=
CONF=
HOSTS=""

usage

if [ -e $EUCALYPTUS/etc/eucalyptus/eucalyptus.conf ]; then
	CONF=$EUCALYPTUS/etc/eucalyptus/eucalyptus.conf
fi


while [ "$#" -gt 0 ]; do
	if [ "$1" = "-c" ]; then
		shift;
		if [ "$#" -lt 1 ]; then
			usage
			exit 1
		fi
		CONF="$1"
		shift
		continue
	fi
	if [ "$1" = "-q" ]; then
		VERBOSE="N"
		shift
		continue
	fi
	if [ "$1" = "-h" ]; then
		usage
		exit 1
	fi
	HOSTS="${HOSTS} ${1}"
	shift
done

# we need the configuration
if [ -n "${CONF}" -a -f "${CONF}" ]; then
	echo "Using ${CONF} as configuration"
fi
. ${CONF}
# we use euca_conf now
if [ ! -x $EUCALYPTUS/usr/sbin/euca_conf ]; then
	echo "Cannot find euca_conf"
	exit 1
fi

# if we don't have hosts on the command line we call -synckeys otherwise
# we do an add node
if [ -n "$HOSTS" ]; then
	$EUCALYPTUS/usr/sbin/euca_conf -addnode "${HOSTS}"
else
	$EUCALYPTUS/usr/sbin/euca_conf -synckeys
fi
