#!/bin/bash

if [ -z "$EUCALYPTUS" ] ; then
	if [ -d /opt/eucalyptus/etc ]; then
		EUCALYPTUS="/opt/eucalyptus"
	else
		EUCALYPTUS="/"
	fi
fi
if [ ! -e $EUCALYPTUS/etc/eucalyptus/eucalyptus.conf ]; then
        echo "EUCALYPTUS is not set"
        exit 1
fi

# add most jars in $EUCALYPTUS/usr/share/eucalyptus
for FILE in $EUCALYPTUS/usr/share/eucalyptus/*.jar; do    
    if [ "$FILE" == "$EUCALYPTUS/usr/share/eucalyptus/commons-logging-1.1.1.jar" ]; then
        continue
    fi

    if [ "$FILE" == "$EUCALYPTUS/usr/share/eucalyptus/commons-logging-api-1.1.1.jar" ]; then
        continue
    fi

    export CLASSPATH=${FILE}:${CLASSPATH}
done

# make sure a couple of them are in the front
export CLASSPATH="$EUCALYPTUS/usr/share/eucalyptus/jcl-over-slf4j-1.5.2.jar:$CLASSPATH"
export CLASSPATH="$EUCALYPTUS/usr/share/eucalyptus/vijava220090625.jar:$CLASSPATH"

DEFINES="-Xbootclasspath/p:$EUCALYPTUS/usr/share/eucalyptus/openjdk-crypto.jar -Djava.security.policy=$EUCALYPTUS/etc/eucalyptus/cloud.d/security.policy -Deuca.home=$EUCALYPTUS -Deuca.var.dir=$EUCALYPTUS/var/lib/eucalyptus -Deuca.conf.dir=$EUCALYPTUS/etc/eucalyptus/cloud.d -Deuca.lib.dir=$EUCALYPTUS/usr/share/eucalyptus -Deuca.log.dir=$EUCALYPTUS/var/log/eucalyptus"
if [ ! -e $EUCALYPTUS/usr/share/eucalyptus/eucalyptus.jar ]; then
  CMD="java $DEFINES com.eucalyptus.cloud.ws.VMwareClient $@"
else
  CMD="java -Djava.system.class.loader=net.jsecurity.classguard.bootstrap.ClassGuard $DEFINES com.eucalyptus.cloud.ws.VMwareClient $@" 
fi

#echo $CLASSPATH
#echo $CMD
$CMD
