#!/usr/bin/perl

delete @ENV{qw(IFS CDPATH ENV BASH_ENV)};
$ENV{'PATH'}='/bin:/usr/bin:/sbin:/usr/sbin/';

$ret = 0;

open(FH, "/etc/xen/xend-config.sxp");
while(<FH>) {
    chomp;
    if ($_ =~ /\(dom0-min-mem (\d+)\)/) {
	print "dom0-min-mem=$1\n";
    }
}
close(FH);
exit $ret;

sub untaint() {
    $str = shift;
    if ($str =~ /^([ &:#-\@\w.]+)$/) {
	$str = $1; #data is now untainted
    } else {
	print STDERR "inputs are tainted\n";
	$str = "";
    }
    return($str);
}
