#!/usr/bin/python -tt
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Redistribution and use of this software in source and binary forms,
# with or without modification, are permitted provided that the following
# conditions are met:
#
#   Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys
import argparse
import logging
import os
import os.path
import stat
import signal

from subprocess import check_call, Popen, PIPE
from ConfigParser import ConfigParser
from StringIO import StringIO
from xml.dom.minidom import parse
from glob import glob
from re import compile, match, I, S

import libvirt

_ETC_EUCALYPTUS = '/etc/eucalyptus'
_RUN_EUCALYPTUS = '/var/run/eucalyptus'
_LIB_EUCALYPTUS = '/var/lib/eucalyptus'
_EUCALYPTUS_CONF = 'eucalyptus.conf'
_GLOBAL_NETWORK_INFO_XML = 'global_network_info.xml'
_WORK = 'work'
_EUCALYPTUS = 'EUCALYPTUS'
_INSTANCE_PATH = 'INSTANCE_PATH'
_GLOBAL_SECTION = 'GLOBAL'
_QEMU_CONN = 'qemu:///system'
_DEFAULT_TIMEOUT = 60
_PACK_TAR = '-pack.tgz'
_INSTANCE_RAM = '-ram.save'
_BLOCK_SAVE = '-block.save'
_LIBVIRT_XML = 'instance-libvirt.xml'
_INSTANCE_XML = 'instance.xml'
_DISCONNECT_ISCSI_PL = '/usr/share/eucalyptus/disconnect_iscsitarget.pl'
_NCHOOK_PATH = '/etc/eucalyptus/nc-hooks/stop-delete.sh'
_STOP_DELETE = r'''
#!/bin/bash
event=$1

if [ "$event" == "euca-nc-pre-clean" ] ; then
    echo "Blocking deletes of storage backing instances"
    exit 1;
fi

exit 0;
'''


class NodeAdminPackError(Exception):

    def __init__(self, *args):
        super(NodeAdminPackError, self).__init__(*args)
        logging.error(*args)


def _time_out(func, args=(), kwargs={}, timeout_duration=1, default=None):
    class TimeoutError(Exception):
        pass

    def handler(signum, frame):
        raise TimeoutError()

    # set the timeout handler
    old_handler = signal.signal(signal.SIGALRM, handler)
    signal.alarm(timeout_duration)
    try:
        result = func(*args, **kwargs)
    except TimeoutError as exc:
        logging.debug("timeout period expired %s", exc)
        result = default
    finally:
        signal.alarm(0)

        if old_handler and old_handler not in [signal.SIG_DFL, signal.SIG_IGN]:
            signal.signal(signal.SIGALRM, old_handler)

    return result


def _parse_args():
    parser = argparse.ArgumentParser(description="Pack an instance from libvirt and "
                                     "place artifacts in an packed file")

    group_i = parser.add_mutually_exclusive_group(required=True)
    group_i.add_argument("--all",
                         help="all instances are targeted for packing",
                         action="store_true")
    group_i.add_argument("-i", "--instance",
                         help="name of the instance target for packing and the target packed file")

    parser.add_argument("-o", "--output-directory",
                        help="location to store resulting packed file(s)",
                        default=".")
    parser.add_argument("--shutdown",
                        help="shutdown the instance first instead of suspend",
                        action="store_true")
    parser.add_argument("--verbose",
                        help="increase output verbosity",
                        action="store_true")
    parser.add_argument("--no-compression",
                        help="skip compression during packing operation",
                        action="store_true")

    args = parser.parse_args()
    loglevel = logging.INFO

    if args.verbose:
        loglevel = logging.DEBUG

    return (args, loglevel)


def _parse_eucalyptus_conf():
    parser = ConfigParser()
    config = StringIO()

    logging.debug("attempting to load %s", os.path.join(
        _ETC_EUCALYPTUS, _EUCALYPTUS_CONF))
    config.write('[%s]\n' % _GLOBAL_SECTION)
    with open(os.path.join(_ETC_EUCALYPTUS, _EUCALYPTUS_CONF)) as config_file:
        config.write(config_file.read())
    config.seek(0, os.SEEK_SET)

    parser.readfp(config)

    return parser


def _list_instances():
    logging.debug("attempting to open %s", _QEMU_CONN)
    conn = libvirt.open(_QEMU_CONN)
    if not conn:
        logging.debug("failed to connect to %s", _QEMU_CONN)
        return None

    return [domain.name() for domain in conn.listAllDomains(0)]


def _get_libvirt_connection():
    conn = libvirt.open(_QEMU_CONN)
    if not conn:
        raise NodeAdminPackError(
            "Failed to connect to libvirt (%s)", _QEMU_CONN)

    return conn


def _lookup_domain(conn, instance_name):
    domain = conn.lookupByName(instance_name)
    if not domain:
        conn.close()
        raise NodeAdminPackError("Failed to find %s in libvirt list of domains",
                                 instance_name)

    return domain


def _modify_libvirt_xml(instance_path):
    with open(os.path.join(instance_path, _LIBVIRT_XML)) as xml_file:
        parser = parse(xml_file)

    with open(os.path.join(instance_path, "%s.orig" % _LIBVIRT_XML), 'wb') as orig_xml_file:
        parser.writexml(orig_xml_file)

    instance_name = None

    for name in parser.getElementsByTagName("name"):
        instance_name = name.firstChild.nodeValue

    for elem in parser.getElementsByTagName("disk"):
        if not elem.getAttribute("type") == "block":
            continue

        if not len(
                elem.getElementsByTagName("source")[0].
                getAttribute("dev").split(instance_name)) == 2:
            continue

        elem.setAttribute("type", "file")

        for driver in elem.getElementsByTagName("driver"):
            driver.removeAttribute("cache")
            driver.setAttribute("name", "qemu")
            driver.setAttribute("type", "raw")

        for source in elem.getElementsByTagName("source"):
            source.setAttribute("file", source.getAttribute("dev"))
            source.removeAttribute("dev")

    with open(os.path.join(instance_path, _LIBVIRT_XML), 'wb') as xml_file:
        parser.writexml(xml_file)


def _find_instance(instance):
    logging.debug(
        "attempting to locate %s in libvirt at %s", instance, _QEMU_CONN)
    conn = _get_libvirt_connection()
    domain = _lookup_domain(conn, instance)

    instances_path = _get_instances_path()

    if domain:
        conn.close()
        instance_path = glob(
            "%s/*/%s" % (os.path.join(instances_path, _WORK), instance))
        if len(instance_path):
            return (instance, instance_path[0])

    conn.close()
    raise NodeAdminPackError("Failed to find instance %s", instance)


def _save_instance(instance, instance_path, *args, **kwargs):
    logging.debug("attempting to save instance %s at %s to %s",
                  instance, _QEMU_CONN,
                  os.path.join(instance_path, "%s%s" % (instance, _INSTANCE_RAM)))
    conn = _get_libvirt_connection()
    domain = _lookup_domain(conn, instance)

    if domain.isActive():
        rc = domain.save(
            os.path.join(instance_path, "%s%s" % (instance, _INSTANCE_RAM)))
        logging.debug("save for domain %s returned %d", instance, rc)

    return 0


def _shutdown_instance(instance, *args, **kwargs):
    logging.debug(
        "attempting to shutdown instance %s at %s", instance, _QEMU_CONN)
    conn = _get_libvirt_connection()
    domain = _lookup_domain(conn, instance)

    if domain.isActive():
        rc = domain.shutdown()
        logging.debug("shutdown for domain %s returned %d", instance, rc)

        if rc:
            raise NodeAdminPackError(
                "Failed attempting to shutdown instance %s %d", instance, rc)

    return 0


def _create_tar(files, pack_path, skip_compression):
    tar_cmd = ["/bin/tar"]

    if skip_compression:
        tar_cmd.extend(["-cpPf", pack_path])
    else:
        tar_cmd.extend(["-czpPf", pack_path])

    tar_cmd.extend(files)

    rc = check_call(tar_cmd)
    if rc:
        NodeAdminPackError(
            "Failed to create packed file with cmd (%s)", tar_cmd)


def _get_eucalyptus_home_path():
    euca_conf = _parse_eucalyptus_conf()

    return euca_conf.get(_GLOBAL_SECTION, _EUCALYPTUS).strip('"')


def _get_instances_path():
    euca_conf = _parse_eucalyptus_conf()

    return euca_conf.get(_GLOBAL_SECTION, _INSTANCE_PATH).strip('"')


def _detach_iscsi_target(volume_id, volume_dev_name, volume_serial, volume_bus, connection_string):
    commas = ',' * 8
    dev_string = "%s%s%s" % (_get_eucalyptus_home_path(),
                             commas, connection_string.encode('utf8'))

    iscsi_pl_cmd = [_DISCONNECT_ISCSI_PL, dev_string]

    rc = check_call(iscsi_pl_cmd)
    if rc:
        raise NodeAdminPackError(
            "Failed to detach iscsi target with connection string %s (%d)", connection_string, rc)
    pass


def _find_volumes_and_detach(instance_path):
    instance_xml = os.path.join(instance_path, _INSTANCE_XML)

    with open(instance_xml) as xml_file:
        parser = parse(xml_file)

    connection_string = ""
    volume_id = ""
    volume_dev_name = ""
    volume_serial = ""
    volume_bus = ""

    for volume in parser.getElementsByTagName('volume'):
        for connectionString in volume.getElementsByTagName('connectionString'):
            connection_string = connectionString.childNodes[0].data
            break

        for vol_id in volume.getElementsByTagName('id'):
            volume_id = vol_id.childNodes[0].data
            break

        for libvirt_node in volume.getElementsByTagName('libvirt'):
            for disk_node in libvirt_node.getElementsByTagName('disk'):
                for target in disk_node.getElementsByTagName('target'):
                    volume_bus = target.getAttribute('bus')
                    volume_dev_name = target.getAttribute('dev')
                    break

                for serial in disk_node.getElementsByTagName('serial'):
                    volume_serial = serial.childNodes[0].data
                    break
                break
            break

        if not volume_id or not volume_serial or not volume_bus or not volume_dev_name:
            raise NodeAdminPackError(
                "Failed collecting information for ebs volumes at instance path %s", instance_path)

        _detach_iscsi_target(volume_id, volume_dev_name,
                             volume_serial, volume_bus, connection_string)


def _gather_files(instance_name, instance_path):
    logging.debug("attempting to gather list of files for archiving at %s for instance %s",
                  instance_path, instance_name)

    if not os.path.exists(os.path.join(instance_path, _GLOBAL_NETWORK_INFO_XML)):
        os.link(os.path.join(_RUN_EUCALYPTUS, _GLOBAL_NETWORK_INFO_XML),
                os.path.join(instance_path, _GLOBAL_NETWORK_INFO_XML))

    for block_file in glob("%s/*.blocks" % instance_path):
        dir_name = os.path.splitext(os.path.basename(block_file))[0]

        if not os.path.exists(os.path.join(instance_path, "%s.dm" % dir_name)):
            logging.debug("Skipping %s as there is no associated .dm file", block_file)
            continue

        with open(os.path.join(instance_path, "%s.dm" % dir_name)) as dm_file:
            device = dm_file.read().split()[-1]

        block_save = "%s%s" % (
            os.path.join(instance_path, dir_name), _BLOCK_SAVE)
        logging.debug(
            "copying block device /dev/mapper/%s to file %s", device, block_save)
        dd_cmd = ['/bin/dd', "if=/dev/mapper/%s" % device,
                  "of=%s" % block_save, "bs=4M"]
        rc = check_call(dd_cmd)
        if rc:
            raise NodeAdminPackError("Failed to copy block device /dev/mapper/%s to file %s (%d)",
                                     device, block_save, rc)

    link_files = glob("%s/link-to-vd*" % instance_path)

    new_links = [("-".join(os.path.basename(os.readlink(link_file)).split('-')[-3:]), link_file)
                 for link_file in link_files]

    for new_link in new_links:
        os.unlink(new_link[1])
        os.symlink(os.path.join(os.path.dirname(new_link[1]), "%s%s" %
                                (new_link[0], _BLOCK_SAVE)), new_link[1])

    target_files = [os.path.join(instance_path, file) for file in os.listdir(instance_path)
                    if os.path.splitext(file)[1] not in
                    [".dm", ".deps", ".sig", ".lock", ".loopback"]]

    return target_files


def pack_instance(instance, output_file, shutdown, skip_compression):
    logging.debug("attempting to pack instance %s", instance)
    instance_tuple = None

    try:
        instance_tuple = _find_instance(instance)
    except NodeAdminPackError:
        logging.debug(
            "instance (%s) not found to have local storage", instance)
        return 1

    logging.debug(
        "found instance tuple %s %s", instance_tuple[0], instance_tuple[1])

    if shutdown:
        rc = _time_out(func=_shutdown_instance,
                       args=[instance_tuple[0]],
                       timeout_duration=_DEFAULT_TIMEOUT)
        if rc:
            raise NodeAdminPackError("Failed attempting to shutdown instance %s %d",
                                     instance, rc)
    else:
        rc = _time_out(func=_save_instance,
                       args=[instance_tuple[0], instance_tuple[1]],
                       timeout_duration=_DEFAULT_TIMEOUT)
        if rc:
            raise NodeAdminPackError("Failed attempting to suspend instance %s %d",
                                     instance, rc)

    tar_files = _gather_files(instance_tuple[0], instance_tuple[1])
    _modify_libvirt_xml(instance_tuple[1])
    _create_tar(tar_files, output_file, skip_compression)

    _find_volumes_and_detach(instance_tuple[1])

    return 0


def _is_nc_service_running():
    service_cmd = ["/sbin/service", "eucalyptus-nc", "status"]

    proc = Popen(service_cmd, stdout=PIPE)
    nc_status = proc.stdout.read()
    logging.debug("nc_status is %s", nc_status)

    results = match(compile(".*running.*", I | S), nc_status)

    return results is not None


def _place_stop_delete_file():
    if os.path.exists(_NCHOOK_PATH):
        return

    with open(_NCHOOK_PATH, 'w') as hook_file:
        hook_file.truncate()
        hook_file.write(_STOP_DELETE)

    os.chmod(_NCHOOK_PATH, stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _main(args, log_level):
    logging.basicConfig(format="%(levelname)s: %(message)s", level=log_level)
    logging.debug("Your Arguments: %s", args)
    rc = 0

    if _is_nc_service_running():
        logging.error(
            "Node controller service is running. Please stop this service before continuing.")
        return 1

    _place_stop_delete_file()

    if args.all:
        logging.debug("packing all instances")
        for instance in _list_instances():
            logging.debug("packing instance %s", instance)
            output_file = os.path.join(
                args.output_directory, instance + _PACK_TAR)
            rc = pack_instance(
                instance, output_file, args.shutdown, args.no_compression)
            if rc:
                logging.warn(
                    "Failed packing instance %s (%d)", instance, rc)
            else:
                logging.info(
                    "Packed instance %s located at %s", instance, output_file)
    else:
        logging.debug("packing instance %s", args.instance)
        output_file = os.path.join(
            args.output_directory, args.instance + _PACK_TAR)
        rc = pack_instance(
            args.instance, output_file, args.shutdown, args.no_compression)

        if rc:
            logging.warn(
                "Failed packing instance %s (%d)", args.instance, rc)
        else:
            logging.info(
                "Packed instance %s located at %s", args.instance, output_file)

    return rc


if __name__ == '__main__':
    args, log_level = _parse_args()
    sys.exit(_main(args, log_level))
