#!/usr/bin/python -tt
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Redistribution and use of this software in source and binary forms,
# with or without modification, are permitted provided that the following
# conditions are met:
#
#   Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys
import argparse
import logging
import os
import os.path
import signal

from subprocess import check_call, Popen, PIPE
from ConfigParser import ConfigParser
from StringIO import StringIO
from xml.dom.minidom import parseString, parse
from re import compile, match, I, S

import libvirt

_ETC_EUCALYPTUS = '/etc/eucalyptus'
_RUN_EUCALYPTUS = '/var/run/eucalyptus'
_LIB_EUCALYPTUS = '/var/lib/eucalyptus'
_EUCALYPTUS_CONF = 'eucalyptus.conf'
_GLOBAL_NETWORK_INFO_XML = 'global_network_info.xml'
_INSTANCE_XML = 'instance.xml'
_INSTANCE_LIBVIRT_XML = 'instance-libvirt.xml'
_WORK = 'work'
_INSTANCE_PATH = 'INSTANCE_PATH'
_EUCALYPTUS = 'EUCALYPTUS'
_GLOBAL_SECTION = 'GLOBAL'
_QEMU_CONN = 'qemu:///system'
_DEFAULT_TIMEOUT = 60
_INSTANCE_RAM = '-ram.save'
_BLOCK_SAVE = '-block.save'
_CONNECT_ISCSI_PL = '/usr/share/eucalyptus/connect_iscsitarget.pl'
_DEFAULT_CEPH_USER = "eucalyptus"
_DEFAULT_CEPH_KEYRING = "/etc/ceph/ceph.client.eucalyptus.keyring"
_DEFAULT_CEPH_CONF = "/etc/ceph/ceph.conf"


class NodeAdminUnpackError(Exception):

    def __init__(self, *args):
        super(NodeAdminUnpackError, self).__init__(*args)
        logging.error(*args)


def _time_out(func, args=(), kwargs={}, timeout_duration=1, default=None):
    class TimeoutError(Exception):
        pass

    def handler(signum, frame):
        raise TimeoutError()

    # set the timeout handler
    old_handler = signal.signal(signal.SIGALRM, handler)
    signal.alarm(timeout_duration)
    try:
        result = func(*args, **kwargs)
    except TimeoutError as exc:
        logging.debug("timeout period expired %s", exc)
        result = default
    finally:
        signal.alarm(0)

        if old_handler and old_handler not in [signal.SIG_DFL, signal.SIG_IGN]:
            signal.signal(signal.SIGALRM, old_handler)

    return result


def _parse_args():
    parser = argparse.ArgumentParser(description="Restore an instance to libvirt after "
                                     "unpacking artifacts from packed file")

    parser.add_argument("packed_file",
                        help="file path to the packed file storing the instance")
    parser.add_argument("--verbose",
                        help="increase output verbosity",
                        action="store_true")

    args = parser.parse_args()

    if args.verbose:
        loglevel = logging.DEBUG
    else:
        loglevel = logging.INFO

    return (args, loglevel)


def _parse_eucalyptus_conf():
    parser = ConfigParser()
    config = StringIO()

    config.write('[%s]\n' % _GLOBAL_SECTION)
    with open(os.path.join(_ETC_EUCALYPTUS, _EUCALYPTUS_CONF)) as config_file:
        config.write(config_file.read())
    config.seek(0, os.SEEK_SET)

    parser.readfp(config)

    return parser


def _find_instance(packed_path):
    tar_cmd = ["/bin/tar", "-xzOf", packed_path,
               "--wildcards", "*/instance.xml"]

    proc = Popen(tar_cmd, stdout=PIPE)
    instance_xml = proc.stdout.read()
    logging.debug(instance_xml)
    parser = parseString(instance_xml)

    for instance_path in parser.getElementsByTagName('instancePath'):
        instance_name = os.path.split(instance_path.childNodes[0].data)[1]
        return (instance_name, instance_path.childNodes[0].data)


def _get_libvirt_connection():
    conn = libvirt.open(_QEMU_CONN)
    if not conn:
        raise NodeAdminUnpackError(
            "Failed to connect to libvirt (%s)", _QEMU_CONN)

    return conn


def _lookup_domain(conn, instance_name):
    domain = conn.lookupByName(instance_name)
    if not domain:
        conn.close()
        raise NodeAdminUnpackError("Failed to find %s in libvirt list of domains",
                                   instance_name)

    return domain


def _restore_instance(instance, instance_path, *args, **kwargs):
    conn = _get_libvirt_connection()
    rc = None

    if os.path.exists(
       os.path.join(instance_path, "%s%s" % (instance, _INSTANCE_RAM))):
        rc = conn.restore(
            os.path.join(instance_path, "%s%s" % (instance, _INSTANCE_RAM)))
    else:
        logging.debug(
            "saved ram file not found, attempting instance creation.")
        with open(os.path.join(instance_path, _INSTANCE_LIBVIRT_XML)) as libvirt_xml:
            instance_xml = libvirt_xml.read()
            conn.createXML(instance_xml, 0)

    if rc:
        raise NodeAdminUnpackError(
            "Failed to restore instance %s at %s (%d)", instance, instance_path, rc)


def _extract_files(packed_path):
    tar_cmd = ["/bin/tar", "-xpf", packed_path, "-C", "/", "--incremental"]

    rc = check_call(tar_cmd)
    if rc:
        raise NodeAdminUnpackError(
            "Failed extracting files from %s (%d)", packed_path, rc)


def _get_eucalyptus_home_path():
    euca_conf = _parse_eucalyptus_conf()

    return euca_conf.get(_GLOBAL_SECTION, _EUCALYPTUS).strip('"')


def _attach_iscsi_target(volume_id, volume_dev_name, volume_serial, volume_bus, connection_string):
    dev_array = [_get_eucalyptus_home_path(), volume_id,
                 volume_dev_name, volume_serial, volume_bus,
                 _DEFAULT_CEPH_USER, _DEFAULT_CEPH_KEYRING, _DEFAULT_CEPH_CONF]

    dev_string = "%s,%s" % (
        ','.join(dev_array), connection_string.encode('utf8'))

    iscsi_pl_cmd = [_CONNECT_ISCSI_PL, dev_string]

    rc = check_call(iscsi_pl_cmd)
    if rc:
        raise NodeAdminUnpackError(
            "Failed to attach iscsi target with connection string %s (%d)", connection_string, rc)
    pass


def _attach_volumes(instance_path):
    instance_xml = os.path.join(instance_path, _INSTANCE_XML)

    with open(instance_xml) as xml_file:
        parser = parse(xml_file)

    connection_string = ""
    volume_id = ""
    volume_dev_name = ""
    volume_serial = ""
    volume_bus = ""

    for volume in parser.getElementsByTagName('volume'):
        for connectionString in volume.getElementsByTagName('connectionString'):
            connection_string = connectionString.childNodes[0].data
            break

        for vol_id in volume.getElementsByTagName('id'):
            volume_id = vol_id.childNodes[0].data
            break

        for libvirt_node in volume.getElementsByTagName('libvirt'):
            for disk_node in libvirt_node.getElementsByTagName('disk'):
                for target in disk_node.getElementsByTagName('target'):
                    volume_bus = target.getAttribute('bus')
                    volume_dev_name = target.getAttribute('dev')
                    break

                for serial in disk_node.getElementsByTagName('serial'):
                    volume_serial = serial.childNodes[0].data
                    break
                break
            break

        if not volume_id or not volume_serial or not volume_bus or not volume_dev_name:
            raise NodeAdminUnpackError(
                "Failed collecting information for ebs volumes at instance path %s", instance_path)

        _attach_iscsi_target(volume_id, volume_dev_name,
                             volume_serial, volume_bus, connection_string)


def _change_ownership(instance_path):
    xml_stat = os.stat(os.path.join(instance_path, _INSTANCE_XML))

    for file in os.listdir(instance_path):
        os.lchown(
            os.path.join(instance_path, file), xml_stat.st_uid, xml_stat.st_gid)

    while(os.path.basename(instance_path).lower() != "eucalyptus"):
        os.lchown(instance_path, xml_stat.st_uid, xml_stat.st_gid)
        instance_path = os.path.dirname(instance_path)


def unpack_instance(instance_path, packed_path):
    _extract_files(packed_path)

    instance_name = os.path.basename(instance_path)

    if not os.path.exists(os.path.join(instance_path, _INSTANCE_LIBVIRT_XML)):
        raise NodeAdminUnpackError("Failed to extract libvirt instance xml file %s",
                                   os.path.join(instance_path, _INSTANCE_LIBVIRT_XML))

    if not os.path.exists(os.path.join(instance_path, "%s%s" % (instance_name, _INSTANCE_RAM))):
        raise NodeAdminUnpackError("Failed to extract ram save file %s",
                                   os.path.join(instance_path, "%s%s" % (instance_name, _INSTANCE_RAM)))

    _change_ownership(instance_path)

    _attach_volumes(instance_path)

    _restore_instance(instance_name, instance_path)
    logging.info("instance %s unpacked", instance_name)

    return 0


def _is_nc_service_running():
    service_cmd = ["/sbin/service", "eucalyptus-nc", "status"]

    proc = Popen(service_cmd, stdout=PIPE)
    nc_status = proc.stdout.read()
    logging.debug("nc_status is %s", nc_status)

    results = match(compile(".*running.*", I | S), nc_status)

    return results is not None


def main(args, log_level):
    logging.basicConfig(format="%(levelname)s: %(message)s", level=log_level)
    logging.debug("Your Arguments: %s", args)

    if _is_nc_service_running():
        logging.error(
            "Node controller service is running. Please stop this service before continuing.")
        return 1

    logging.info("unpack on %s", args.packed_file)

    if not os.path.exists(args.packed_file):
        raise NodeAdminUnpackError("%s not found", args.packed_file)

    instance_tuple = _find_instance(args.packed_file)

    if instance_tuple:
        rc = unpack_instance(instance_tuple[1], args.packed_file)

        if rc:
            raise NodeAdminUnpackError("unpack instance returned %d", rc)

    return 0


if __name__ == '__main__':
    args, log_level = _parse_args()
    sys.exit(main(args, log_level))
