#!/bin/bash

# Copyright 2014 Eucalyptus Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

###set -e # exit on error
set -x # echo lines
SCRIPT_DIR=$(dirname $(readlink -f ${BASH_SOURCE}))

if [ -z "$EUCALYPTUS" ] ; then
	export EUCALYPTUS=$(echo $SCRIPT_DIR | sed 's/\/storage//')
	echo $EUCALYPTUS
fi

if [ -z "$VDDK_HOME" ] ; then
   export VDDK_HOME=/opt/eucalyptus/packages/vddk
fi
if [ ! -e $VDDK_HOME ] ; then
   echo "please set VDDK_HOME environment variable"
   exit 1
fi

export PATH="$EUCALYPTUS/usr/lib/eucalyptus:$PATH" # to ensure euca-imager has euca_rootwrap
if [ -z `which euca_rootwrap` ] ; then
   echo "euca_rootwrap is not found in your PATH!"
   exit 1
fi

IMAGER_BIN=${SCRIPT_DIR}/euca-imager
if [ ! -x ${IMAGER_BIN} ] ; then
   echo "euca-imager not compiled in $SCRIPT_DIR"
   exit 1
fi

#if [ `uname -m` == "x86_64" ] ; then
#   PRELOAD=$VDDK_HOME/lib/vmware-vix-disklib/lib64/libcurl.so.4
#else
#   PRELOAD=$VDDK_HOME/lib/vmware-vix-disklib/lib32/libcurl.so.4
#fi

#export LD_LIBRARY_PATH="$VDDK_HOME/lib:$VDDK_HOME/lib/vmware-vix-disklib/lib32:$VDDK_HOME/lib/vmware-vix-disklib/lib64/"
#IMAGER=LD_PRELOAD=${PRELOAD} ${IMAGER_BIN}
IMAGER=${SCRIPT_DIR}/euca-imager

EMI1=EMI-AAA111

# create temporary directories for this test to use
TS=$((`date +%s`-1320985978))
LOG_DIR=${SCRIPT_DIR}/test_imager_${TS}
WORK_DIR=${SCRIPT_DIR}/test_imager_${TS}/work
CACHE_DIR=${SCRIPT_DIR}/test_imager_${TS}/cache
mkdir -p ${WORK_DIR}
mkdir -p ${CACHE_DIR}

# create a partition to feed to the imager
KERNEL=`ls -1 /boot/vmlinuz* | tail -1`
if [ "$KERNEL" == "" ] ; then
    echo "failed to find local kernel to use"
    exit 1
fi
RAMDISK=`ls -1 /boot/initrd* | tail -1`
if [ "$RAMDISK" == "" ] ; then
    echo "failed to find local ramdisk to use"
    exit 1
fi
PARTITION=${SCRIPT_DIR}/centos.5-5.x86-64.img
if [ ! -e $PARTITION ] ; then
    PARTITION=${LOG_DIR}/partition.img
    dd if=/dev/zero of=${PARTITION} bs=512 count=20480 # 10MB
    DEVICE=`losetup -f`
    losetup $DEVICE ${PARTITION}
    if ! mkfs.ext3 $DEVICE ; then
	echo "failed to create empty file system in $PARTITION"
	losetup -d $DEVICE
	exit 1
    fi
    sync
fi

CMD="$IMAGER debug=yes
work=${WORK_DIR} 
cache=${CACHE_DIR}
work_size=53687091200
cache_size=53687091200

prepare
id=${EMI1}
out=${EMI1}.dsk
boot=true
work=false
cache=true
vbr=machine:${EMI1}:-1:none:sda1:file://${PARTITION}
vbr=kernel:EKI-000AAA:-1:none:none:file://${KERNEL}
vbr=ramdisk:ERI-000AAA:-1:none:none:file://${RAMDISK}"

UNUSED="
vbr=ephemeral0:none:1072128:ext3:sda3:none
vbr=swap:none:524288:swap:sda2:none

convert
in-type=disk
out-type=vmdk

upload
login=root
password=foobar
vsphere-datacenter=ha-datacenter
vsphere-vmdk=[datastore1]testvm/testvm.vmdk
vsphere-vmx=[datastore1]testvm/testvm.vmx
out=https://192.168.33.5
in-type=vmdk"

${CMD} >>${LOG_DIR}/cmd0.txt 2>&1
find $LOG_DIR
sleep 2

#${CMD} >>${LOG_DIR}/cmd0.txt 2>&1 &
#find $LOG_DIR
#sleep 2

exit
wait

# 3 iterations of the cleanup routine
dmsetup table | cut -d':' -f 1 | sort | uniq | xargs -L 1 dmsetup remove ; losetup -a | cut -d':' -f 1 | xargs -L 1 losetup -d; losetup -a
dmsetup table | cut -d':' -f 1 | sort | uniq | xargs -L 1 dmsetup remove ; losetup -a | cut -d':' -f 1 | xargs -L 1 losetup -d; losetup -a
dmsetup table | cut -d':' -f 1 | sort | uniq | xargs -L 1 dmsetup remove ; losetup -a | cut -d':' -f 1 | xargs -L 1 losetup -d; losetup -a
