# Makefile for eucalyptus/net
#
# $Id: Makefile,v 1.5 2008-12-24 18:28:07 nurmi Exp $
#

include ../Makedefs

all: vnetwork.o

build: all

.c.o:
	$(CC) -c $(CFLAGS) $(INCLUDES) $<

clean:
	rm -rf *~ *.o test

distclean:

install:

deploy:
